SELECT CONTENT,SANGPGNUM,TITLE,SANGCODE
		FROM JUMUNPAGE JOIN PRODUCT 
			USING(SANGCODE)
			WHERE SANGPGNUM=1;
			
SELECT S.SANGCODE,S.SANGNAME,G.SANGPNAME,G.TITLE,G.CONTENT FROM PRODUCT 
		 S, JUMUNPAGE G WHERE S.SANGCODE LIKE 'WA%' 
		AND S.SANGCODE=G.SANGCODE;
--상품 목록용 이미지 입력
INSERT INTO PRODUCTIMG(SEQ,SANGPGNUM,IMGNAME,SAVENAME,IMGPATH)
VALUES(PRODUCTIMG_SEQ.NEXTVAL,'1','1','1','1');
--IMGPATH,TITLE,PRICE
SELECT IMGPATH,TITLE,PRICE
	FROM JUMUNPAGE JOIN PRODUCTIMG
	USING(SANGPGNUM) 
	JOIN PRODUCT 
	USING (SANGCODE);
	
SELECT IMGPATH FROM PRODUCTIMG;

SELECT G.SANGPGNUM SANGPGNUM, S.SANGCODE SANGCODE,S.SANGNAME SANGNAME,
		G.SANGPNAME SANGPNAME,G.TITLE TITLE,G.CONTENT CONTENT,S.PRICE PRICE,
		FROM PRODUCT S, JUMUNPAGE G 
		WHERE S.SANGCODE LIKE '%DU%' 
		AND S.SANGCODE=G.SANGCODE;
		
SELECT SANGPGNUM,SANGCODE,SANGPNAME,IMGPATH,TITLE,PRICE
	FROM JUMUNPAGE JOIN PRODUCTIMG
	USING(SANGPGNUM) 
	JOIN PRODUCT 
	USING (SANGCODE)
	WHERE SANGCODE LIKE '%DU%';	
	