SELECT CONTENT,SANGPGNUM,TITLE,SANGCODE
		FROM JUMUNPAGE JOIN PRODUCT 
			USING(SANGCODE)
			WHERE SANGPGNUM=1;
			
SELECT S.SANGCODE,S.SANGNAME,G.SANGPNAME,G.TITLE,G.CONTENT FROM PRODUCT 
		 S, JUMUNPAGE G WHERE S.SANGCODE LIKE 'WA%' 
		AND S.SANGCODE=G.SANGCODE;